### ISSUE TITLE
Safari: issues with build 2.1.0.12 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#174]
1) Safari: poesialatina.it does not work any longer: tools are activated but double-clicking is not working and no pop-up is generated, also reloading the page does not do anything. this used to work in previous builds.
2) Safari: on reload, the info panel is generated in all sites. in Chrome (previous build) the inflection table or the define panel  or the Grammar (the latest open panel) is generated.
3) Safari: notice that occasionally it takes one more click to activate the tools. 
4) also when browsing through pages, the red icon goes on and off until it is on.

**Comment by balmas** [comment]
1. Re poesialatina.it : @kirlat it seems this is because that site reports 0 as the body.clientHeight value. I am afraid this isn't going to be a reliable measure to use to determine if the frame is big enough to host Alpheios content.  MDN says this property "is zero for elements with no CSS or inline layout boxes;" so I think we either need to find another way to restrict use.  I wonder about the following: since the main point of this is to prevent Alpheios from being activated in subframes, could we either (1) only test the height if we are actually in a frame (which still isn't foolproof of course but kicks the problem down a bit or (2) keep track in the background of how many times Alpheios is being activated upon navigating to a new page, and just only allow 1?

2. @kirlat We should restore both panel state and last active panel tab. Not positive how this change caused that behavior to break.

3. @monzug can you reproduce the needing more than one click only on specific sites? 

4. We may not be able to do too much about this.

**Comment by monzug** [comment]
FF: poesialatina.it, it.wikibooks.org 1) on reload, no pop-up is generated 2) go to a new page, no panel is generated
Chrome: poesialatina. it 1) on reload, only info panel is generated (no matter which panel was on before) 2) go to a new page, no panel is generated

@balmas as per issue 3, I have seen it few times soon after installation.

**Comment by kirlat** [comment]
>     1. (2) keep track in the background of how many times Alpheios is being activated upon navigating to a new page, and just only allow 1

This would bring a high complexity price, because this can be tracked only in background (content scripts are isolated from one another and only background know how many of them run through content state messages). So we'll have to:
* Add an activation counter for each tab to the background script
* Store each frame's URL so we'll be able to distinguish between them (and URL might be an ID not reliable enough because in some tricky cases, I'm afraid, frames can have the same URL)
* Add target URL to our communication protocol so that when we send a message to a content script it would know which content script in which frame it targets.
* Modify content script so it will be able distinguish between messages sent to its own URL and to other URLs.

Even then, this would result in several panels opened when a page is loaded and only after that some them will be closing. Would really love to avoid that. Will try to find a solution within (1). Maybe we don't really need to test the height at all as the cases I've tested with usually had both width and height to be zero (do we need a crawler that will gather information about width and height of all our target pages? 🙂 ). Maybe testing for non-zero width and some characters present should be enough.

poesialatina.it, in particular, has a height of zero because all inner elements has either fixed or absolute positions. As a result, body has no height.

**Comment by balmas** [comment]
ok.  you have convinced me that going down the counter road would be a bad idea!

**Comment by balmas** [comment]
issues 1 and 2 should be fixed in build 2.0.1.13 which is available in Dropbox for Safari and from https://github.com/alpheios-project/webextension/tree/release-2.1.0.x/dist from FF and Chrome.

Note on item 2, panel tab state: we cannot always restore the state of the panel tab on a new page. For example, if we are viewing an inflection table which is the result of a query, that tab is no longer available. on the new page. Similarly, the grammar may not be available. We have decided in this case, if the tab that was previously active cannot be displayed, we display the info tab by default.

There remains instability and inconsistent behavior with activation state across tabs and new pages in Safari, as discussed in #160. We may need to let these go for the initial Safari release, but we need to verify that that this is still working well and consistently in FF and Chrome.

**Comment by monzug** [comment]
poesialatina.it: after installing the latest build, I was able to activate the tools with the info panel opened, also double-clicking works fine. However, as soon as I browse away from the page, the tools are deactivated and I am not able to activate the webextension any longer: double clicking and reloading the page do not produce any results.

**Comment by kirlat** [comment]
Do I understand correctly that the issue is that a Safari icon becomes disabled (i.e. the icon in a red circle disappears)? What happens to the functionality of an extension then? Would it show a popup if one doubleclick a word? How did a browse away happen: did you click on the link on a page, or did you enter a new URL into the address bar, or did you switch to some other app.

I did some extensive testing on poesialatina.it today and, generally, it was working fine for me except for one occasion, which I'll describe later. There were some sites that, if to click on the link on their pages, would open content in a new tab. In that case the icon will be deactivated on a new tab, which is an expected behavior: if we open a new window (tab), the default state is "disabled". However, we can click on the icon, and it will bring up an extensions. So that seems to work correctly to me.

The occasion when I've seen the icon becomes inactive was when I was switching to some other app window (i.e. from Safari to Firefox or Chrome) and stayed in that new window for long enough (maybe a minute, but hard to say exactly). Then, if to return back to Safari, an activation icon would be gone. But the content script would be still active. So if one double click on a word, a popup would be brought up, and the icon would become active at that moment (as content script will send a state message to background and the background would update the icon state).

I've started to search for an explanation, and found an interesting thread that might explain this behavior: https://forums.developer.apple.com/thread/110979. It seems that Safari do deactivate extension after a while. In the topic a Safari rep says it can be after 15 seconds or longer, depending on a situation. As a result of this deactivation, I think, the icon is disabled, as in our case. And it seems there will be no solution to this as of now except for a content script to ping a background every 15 (?) seconds. But that's really ugly, on my opinion.

It seems that Safari app extension API is a half baked product at the moment. I stumbled upon the other thread (https://forums.developer.apple.com/thread/105817) where a Safari rep is saying that an app extension API is still developing some features:
> 2) We are working on an API for this and hope to have it available for extensions soon.

So we might expect some change in the future.

It's also frustrating that terminology seems not always be clear too. If it's said that an "extension" is deactivated, would that mean a content script, or an app extension code that was injected by the host app, or the host app itself. There are many parts that build an extension, and I've not seen any clear architectural diagram describing their interactions in a way detailed enough to be suitable to base dev decisions on it. Hope it will change for better in the future.

@monzug, was the issue you've discovered related to switching to some other application window? If not, is it possible to formulate any exact steps to reproduce it?

**Comment by monzug** [comment]
@kirlat  yes, still the same problem that has been reported in issue #160 related to switching to an other browser.  what's left to test in this bug is the panel state in FF and Chrome.

**Comment by kirlat** [comment]
OK, the problem with icon being deactivated after switching to the other app we could probably solve by making content script to ping background periodically (i.e. sending a state request once a couple of seconds). This is definitely not perfect technically, but within Safari App Extension bounds that's probably the best we can do. @balmas, what do you think?

**Comment by balmas** [comment]
I think that is not ideal, but might be okay. Could we limit the pinging to when the extension is in the "activated" state?

**Comment by monzug** [comment]
Panel state in FF, tested in 2 sites, poesialatina.it and thelatinlibrary.com
build 2.1.0.13 vs 2.0.2.20, differences below:
on install and then on reload, no panel opened (info panel in 2.0.2.20)
inflection table and grammar with chapter viewed, on reload info panel is generated (old build opens the verb browser or the grammar panel)
lookup, reload, no panel  (old build opens definitions panel)
no panel, reload, no panel  (old build opens the last viewed panel)
disable/enable, no panel is generated (old build: disable/enable tools open the last viewed panel)

**Comment by monzug** [comment]
Panel state in Chrome, tested in 2 sites, poesialatina.it and thelatinlibrary.com
build 2.1.0.13 vs 2.0.2.20, differences below:
on reload after installation, no panel opened (info panel in 2.0.2.20) - there is an improvement compare with old build as the info panel is generated after installation in poesialatina.it, this was not working in 2.0.2.20
inflection table and grammar with chapter viewed, on reload info panel is generated (old build opens the verb browser or the grammar panel)
lookup, reload, no panel (old build opens definitions panel)
no panel, reload, no panel (old build opens the last viewed panel)
disable/enable, no panel is generated (old build: disable/enable tools open the last viewed panel)

**Comment by monzug** [comment]
will edit my comments above about the reloading after installation. it does not make much sense as it's one of the situation listed later.

**Comment by monzug** [comment]
@balmas - I remove the comments on installation and reloading as they are also reported later. so the only issue is the panel not generated on activation. I checked that Panel on activate is checked in Options.

**Comment by monzug** [comment]
1) yes.

**Comment by kirlat** [comment]
I'm on it. Added the ping already, investigating a panel issue now. Thanks for detailed description of the issues, very helpful!

**Comment by monzug** [comment]
see also some explanation from Bridget added to issue #166

**Comment by balmas** [comment]
Hopefully mostly fixed in build 2.1.0.14 although panel state upon page navigation is now broken again in Safari at least. Passing to @monzug to verify what she can.

**Comment by monzug** [comment]
Thanks! Mostly ping works. I added a comment about this in /components/issues/254.
panel is generated when tools are activated for first time. any subsequent activation, panel is not longer generated. in Chrome and FF

**Comment by balmas** [comment]
maybe my fix for panel state in chrome and ff wasn't correct. @kirlat can you review?

**Comment by balmas** [comment]
In build 2.1.0.15 Dropbox for Safari and https://github.com/alpheios-project/webextension/tree/qa-2.1.0.15/dist for FF and Chrome 

expect the behavior as described at https://github.com/alpheios-project/webextension/tree/release-2.1.0.x#usage-scenarios

I believe this should be working in all browsers, except I see that there is a slight discrepancy with the following scenario:

*On the same page: activated, deactivated, then activated again*
In this case an extension should should reset its state to a default one right before the second activation: deactivation should always reset a webextension state to default.

What I see is if you deactivate and reactivate the extension, *within the same tab* upon reactivation the state of the panel on deactivation trumps the panelOnActivate. But if open a new tab and activate Alpheios, the panelOnActivate setting is respected.

I am fine with this behavior for release. Passing to @monzug to verify.

**Comment by monzug** [comment]
besides the above scenario described by Bridget, here is an other one that does not work as supposed:
1)  Activated, navigate to the new page
When an extension is activated, and user navigates to the other page, the webextension retains its active state, as well as whether a panel is open or not and what tab is active within a panel.
in loebclassics in Chrome, the tools are still active when navigating to a new page but the info panel is not generated.
tested in build 2.1.015 chrome and safari

**Comment by balmas** [comment]
can you retest in build 2.1.0.16?

**Comment by monzug** [comment]
I will but the quick test I did in safari, it worked as in build 15.  I am
installing it right now on chrome and ff

**Comment by monzug** [comment]
definitely, it does not work in loebclassics (tested in Chrome, FF and Safari).
e.g.
- open new loebclassic page and activate the tools. tools are activate and info panel is generated.
- go to authors page, info panel is generated again. select any author and open any related books. No panel generated. double click any word and open inflection page (or define or grammar), go to the next page of the book, no panel is generated

it does work in the following scenario:
- poesialatina.it, open a greek author page and activate the tools. info panel is generated
- in the browser, change the url to browse to an other page, the info panel is generated in the new page. if I go to a new page via menu items, the info panel is not generated.

**Comment by balmas** [comment]
Ah, okay, I think we are running into the known limitation that if you use page elements to navigate to a new page, the clickaway directive we have active in Alpheios, in which clicking outside of the panel or popup closes them both, takes effect before the page navigation, so that the status is changed to closed first.  There isn't anything we can do about this right now.  If that's the only thing that's not working, I am okay with releasing it.

**Comment by monzug** [comment]
this used to work on previous release 2.0.2.20 (just re-tested in chrome). I still have to test other issues.

**Comment by balmas** [comment]
I think it was actually broken in the previous release, in that we didn't retain state properly between pages.

**Comment by kirlat** [comment]
>     1. Activated, navigate to the new page
>        When an extension is activated, and user navigates to the other page, the webextension retains its active state, as well as whether a panel is open or not and what tab is active within a panel.
>        in loebclassics in Chrome, the tools are still active when navigating to a new page but the info panel is not generated.

@monzug, how do you navigate to other pages? Do you click on a link on a page or use page's menu? If so, then it is working as expected, I think: clicking anywhere on a page closes a panel automatically and this closed panel state is transferred to the other page. As @balmas noted, it was broken in the previous release as it was not respecting the closed state on a new page but rather was activating an extension with the default settings which command to open a panel. So the previous version produced a desired result (in this particular case only, probably), but not an expected one.

What happen if you activate an extension, navigate a couple of pages forward (the panel will be closed during this because of a clickaway directive), then open a panel, and user browser's "back" button to return to previous pages? In my tests it is keeping a panel and tab state properly. After that you could try to go back and forward across pages using browser's back and forward buttons (not clicking anywhere on a page as it will close a panel). The panel should retain its state. The other equivalent would be to copy new page's url into a browser's URL bar. Panel should keep its state. I would not expect anybody doing that, but that proves if panel is closed because of a clickaway or not.

Clicking anywhere outside of the panel closes it. This is an expected behavior for us now.

**Comment by monzug** [comment]
yes, it works as you described so well. Thanks.
I just reported all the differences between current release builds and  2.0.2.20. glad that the problem is in the old one....
